// K.N.S GP College Survival Simulator
const MAX_DAYS = 20;
const SAVE_KEY = 'knsgpCollegeSurvivalSave';

const events = [
  { title:'Morning Class', description:'8:00 AM ki class hai... aur tumhari aankh 8:15 AM par khuli. 😭', choices:[['🏃 Run to college',{attendance:5,energy:-8,happiness:-2},'Tum class pahunch gaye... lekin attendance already ho chuki thi. 😂'],['😴 Sleep again',{energy:15,brain:-5,attendance:-5},'Attendance gayi, sleep quality aayi. Priorities clear hain. 😴'],['📱 Friend se attendance mangwao',{battery:-8,happiness:3,attendance:2},'Friend ne attendance laga di. Dosti abhi zinda hai. 🤝']]},
  { title:'Computer Lab', description:'Code run nahi ho raha aur sir tumhari taraf dekh rahe hain. 💀', choices:[['💻 Debug karo',{brain:8,energy:-7,happiness:2},'Bug gaya nahi, par tumhara confidence zaroor aa gaya. 💻'],['🔄 Restart VS Code',{battery:-4,brain:2},'VS Code restart hua. Problem ne bhi restart hone se mana kar diya. 💀'],['🤝 Friend se help lo',{happiness:5,brain:4},'Teamwork ne code ko zinda kar diya. Aaj ka lab bach gaya!'],['😂 Sir ko bolo System problem hai',{happiness:4,attendance:-2},'System problem accepted. Sir ka expression abhi bhi loading hai. 😂']]},
  { title:'Canteen', description:'Canteen me chai + samosa tumhe emotional support de rahe hain. ☕😂', choices:[['☕ Chai + Samosa',{money:-50,happiness:10,energy:3},'₹50 chai me chale gaye. Financial condition: Critical 😂'],['💰 Paisa bachao',{brain:2,happiness:-3},'Paisa bach gaya, par samosa tumhe yaad karta rahega.'],['🤝 Friend se treat maango',{happiness:7,energy:3},'Friend ne treat di. Agli baar tumhari baari... theoretically. 😌']]},
  { title:'Viva', description:'Viva hai. Tumne sirf topic ka naam padha hai. 😭', choices:[['😎 Confidence se jao',{happiness:8,brain:-2},'Viva me answer nahi aaya, lekin confidence 100% tha. 😎'],['📚 Last-minute revision',{brain:10,energy:-8,happiness:-3},'Sir ne wahi question puch diya jo nahi padha. Classic. 😂'],['😂 Bhagwan bharose',{happiness:4,brain:-5},'Answer divine tha. Marks ka result abhi divine mystery hai. 🙏']]},
  { title:'Surprise Test', description:'Teacher: “Aaj ek chhota sa test hoga.” Chhota sirf naam me hai. 😳', choices:[['🧠 Attempt karo',{brain:7,energy:-5,happiness:2},'Paper attempt kiya. Kuch answers tumne aur paper ne milkar banaye.'],['👀 Guess karo',{brain:-2,happiness:4},'Guessing skills: underrated. Result: confidential. 👀'],['😂 Luck par bharosa',{happiness:5,brain:-4},'Luck ne attendance ki tarah tumhe bhi thoda ignore kar diya.']]},
  { title:'Attendance Crisis', description:'Attendance 75% se neeche jaane wali hai. Ab asli thriller shuru. 📚', choices:[['🏫 Class attend karo',{attendance:7,energy:-7,brain:3},'Tum class me present the. Mentally? Ispe research chal rahi hai.'],['📚 Assignment complete karo',{attendance:3,brain:7,energy:-5},'Assignment submit. Teacher impressed, tum exhausted.'],['😎 Risk le lo',{attendance:-7,happiness:7},'Risk liya. Attendance register ne tumhe personally yaad rakha. 😬']]},
  { title:'Phone Battery', description:'Phone battery 4% hai aur charger room me hai. Modern survival test. 🔋', choices:[['🔌 Charging point dhundo',{battery:30,energy:-3},'Charging point mila. Phone aur tum dono bach gaye. 🔌'],['📱 Phone band karo',{battery:10,brain:3,happiness:-2},'Phone off. Ab tum apne thoughts ke saath akele ho.'],['😂 4% me pura din survive karo',{battery:-4,happiness:8},'4% ne poora din nahi dekha, par tumne dekha. Respect. 😂']]},
  { title:'Assignment Panic', description:'Assignment kal submit karna hai aur abhi tak first page bhi nahi bana. ✍️', choices:[['✍️ Start now',{brain:8,energy:-9,happiness:-2},'First page ban gaya. Ab bas 11 pages aur aur ek miracle.'],['🤝 Friend se discuss karo',{brain:5,happiness:6},'Discussion ke baad assignment ka topic bhi clear ho gaya. Win!'],['😴 Kal dekhenge',{energy:10,brain:-5,happiness:3},'Kal ka tum aaj ke tum se naraz hai. 😴']]},
  { title:'Bus Missed', description:'College ki bus aankhon ke saamne chali gayi. Driver ne cinematic exit liya. 🚌', choices:[['🏃 Auto pakdo',{money:-80,energy:-7,attendance:4},'Auto wale bhaiya ne tumhari attendance bachai, wallet nahi.'],['🚶 Walk to college',{energy:-12,attendance:3,happiness:4},'Walk of fame nahi, walk of attendance tha.'],['📞 Friend ko call karo',{battery:-10,happiness:5},'Friend rescue operation successful. Dosti ke marks +10.']]},
  { title:'Rainy Campus', description:'Baarish ne campus ko swimming pool bana diya. Notes waterproof nahi the. 🌧️', choices:[['☔ Umbrella share karo',{happiness:8,attendance:3},'Umbrella chhota tha, friendship badi ho gayi.'],['🏃 Run through rain',{energy:-8,happiness:6,attendance:4},'Tum bheege, par dramatic entry successful rahi.'],['🏠 Room wapas',{attendance:-6,energy:10,happiness:-2},'Baarish jeet gayi. Tumne blanket ko attendance proxy bana liya.']]},
  { title:'Group Project', description:'Group project me sab members online hain. Kaam karne wala koi online nahi. 👥', choices:[['🧠 Leader ban jao',{brain:6,energy:-8,happiness:-3},'Leader ban gaye. Ab group tumhe “bhai” kehkar kaam dega.'],['🤝 Work divide karo',{brain:5,happiness:7},'Kaam divide hua. Group chat pe pehli baar silence nahi, progress thi.'],['😂 Seen karke chhod do',{happiness:5,attendance:-2,brain:-3},'Seen kar diya. Project ne bhi tumhe seen kar diya.']]},
  { title:'Library Mission', description:'Library me silence hai, lekin tumhare dimaag me DJ night chal rahi hai. 📖', choices:[['📖 Focus se padho',{brain:10,energy:-6,happiness:2},'Brain ne 10 points gain kiye. DJ ne interval liya.'],['😴 Table par nap',{energy:12,brain:-3,happiness:5},'Library ki book khuli rahi, tumhari aankhen band. Productive-ish.'],['📱 Reels dekh lo',{battery:-12,happiness:9,brain:-6},'Algorithm ne tumhe topper nahi, watcher zaroor bana diya.']]},
  { title:'Hostel Mess', description:'Aaj mess me dish ka naam “Surprise Curry” hai. Surprise kaafi strong hai. 🍛', choices:[['🍛 Kha lo',{energy:5,happiness:3},'Taste mysterious tha, par pet ne ceasefire sign kar liya.'],['🥪 Bahar se mangao',{money:-100,energy:7,happiness:8},'₹100 gaya, taste buds khush hue. Wallet ne condolence bheja.'],['😅 Biscuit se kaam chalao',{money:-20,energy:-4,happiness:2},'Biscuit dinner. Minimalism ka sabse crunchy version.']]},
  { title:'Lab Partner Trouble', description:'Tumhara lab partner bol raha hai: “Bhai, tu kar le na, mujhe jaldi jaana hai.” 😐', choices:[['💻 Khud complete karo',{brain:8,energy:-8,attendance:2},'Lab tumne bachaya. Partner ne sirf screenshot liya.'],['🤝 Negotiate karo',{happiness:4,brain:3},'Deal ho gayi: code tumhara, credit dono ka. Business!'],['😎 Sir ko bata do',{attendance:4,happiness:-4},'Truth bola. Partner ne tumhe group se remove kar diya.']]},
  { title:'Cultural Fest', description:'Fest me DJ loud hai, assignments louder. Campus me choices hi choices. 🎤', choices:[['🎤 Fest enjoy karo',{happiness:15,energy:-6,attendance:-2},'Padhai kal bhi hogi. Aaj dance ka attendance full tha.'],['📚 Assignment karo',{brain:6,energy:-6,happiness:-4},'Tumne assignment kiya. DJ ne tumhe respect se dekha.'],['📸 Photos click karo',{battery:-12,happiness:10},'Photos itne aaye ki phone ne bhi memories maang li.']]},
  { title:'Professor Surprise', description:'Sir ne bola “tumse kuch poochna hai.” Heart rate ne attendance cross kar li. 😨', choices:[['😎 Seedha answer do',{brain:5,happiness:5},'Answer aadha sahi tha, confidence poora.'],['🤫 Quiet mode',{happiness:-3,attendance:-2},'Tum invisible banna chahte the. Sir ne phir bhi dekh liya.'],['📚 Topic revise karo',{brain:8,energy:-5},'Topic yaad aa gaya. Brain ne aaj overtime kiya.']]},
  { title:'Wallet Crisis', description:'Wallet me sirf ₹120 bache hain. Month abhi emotional phase me hai. 💸', choices:[['💰 Budget banao',{money:20,brain:3,happiness:-2},'Budget ban gaya. Chai ka budget ab feelings me hai.'],['☕ Last chai treat',{money:-40,happiness:9},'Last chai ne first-class emotional support diya.'],['🤝 Udhari maango',{money:60,happiness:4},'Udhari mili. Ab kal ka tum aaj ke tum ko judge karega.']]},
  { title:'Exam Timetable', description:'Exam timetable aa gaya. Pehla paper wahi hai jo tumne “baad me” rakha tha. 📅', choices:[['📅 Schedule banao',{brain:8,energy:-4,happiness:2},'Schedule ban gaya. Follow kaun karega, ye next semester ka question hai.'],['🧠 Crash study',{brain:12,energy:-12,happiness:-5},'Brain power up, energy power down. Academic rollercoaster!'],['😂 Timetable ignore karo',{happiness:8,brain:-7},'Ignore karne se timetable gayab nahi hua. Kaash.']]},
  { title:'Final Prep', description:'Semester ka end nazdeek hai. Tumhari files, notes aur hopes sab scattered hain. 🗂️', choices:[['🗂️ Notes organize karo',{brain:8,energy:-6,happiness:3},'Notes organize. Ek folder me tumhara future bhi mil gaya.'],['🤝 Group revision',{brain:7,happiness:6,energy:-5},'Group revision me 20% study, 80% snacks. Perfect ratio.'],['😴 Power nap',{energy:15,brain:-4,happiness:5},'Nap ne tumhe restore kiya. Notes ne tumhe miss kiya.']]},
  { title:'Last Day Chaos', description:'Final day hai! Attendance, brain, energy... sab tumhe dekh kar score calculate kar rahe hain. 🎓', choices:[['🎓 All-in class',{attendance:6,brain:5,energy:-8,happiness:4},'Last class me present. Semester ko proper goodbye mila.'],['☕ Canteen celebration',{money:-70,happiness:12,energy:3},'Semester ka last samosa emotional tha. Paisa less emotional.'],['🏆 Survive in style',{brain:3,attendance:2,happiness:10},'Style me survive kiya. Ab result screen tumhari wait kar rahi hai.']]}
];

const resultMessages = ['Aaj ka decision questionable tha, par memorable zaroor tha. 😂','Tumne adulting try ki. College ne counter-attack kar diya.','Attendance register ne tumhe dekha aur sigh kiya.','Brain power thoda gaya, life experience thoda aaya.','Aaj tum hero nahi, par supporting character bhi nahi the.','Campus me tumhara legend level +1 hua.','Sir ne kuch nahi bola. Ye definitely good sign hai... shayad.','Financial condition: chai ke bharose. ☕','Tumne problem solve nahi ki, par uske saath negotiate zaroor kiya.','Dost ne help ki. Notes abhi bhi missing hain. 🤝','Aaj ka din “kal se pakka padhunga” ke naam.','Code nahi chala, par tumhara patience bhi nahi chala. 💀','Tumhara confidence result se kaafi aage chal raha hai.','Mood: semester ke end jaisa.','K.N.S GP me survival skill unlock ho gayi!','Tumne academic damage ko stylishly absorb kiya.','Ye decision future-you ko explain karna padega.','Ek aur din, ek aur unexpected plot twist.','Tumhari strategy questionable, execution iconic.','College ne tumhe test kiya, tumne college ko meme bana diya.','Aaj ka attendance tumhare favour me tha. Miracle!','Battery low, spirit high. Classic student energy.','Paisa gaya, par ek memory reh gayi.','Notes ne aaj tumhe finally accept kiya.','Tumne shortcut liya. Destination abhi bhi college hai.','Aaj tumne “jugaad” ko official skill bana diya.','Energy low hai, lekin semester bhi low hai.','Result kuch bhi ho, story interesting hai.','Tumhari degree ka plot thick ho raha hai.','Survival meter ne tumhe thumbs up diya. 👍','Aaj ka chaos kal ki funny story banega.'];

let game = { name:'', day:1, stats:{money:1000,battery:80,brain:70,energy:70,attendance:75,happiness:60}, history:[], currentEvent:null, finished:false };
let audioContext;
const $ = id => document.getElementById(id);

function clamp(value, min, max){ return Math.max(min, Math.min(max, value)); }
function playSound(type='click'){ try { audioContext = audioContext || new (window.AudioContext || window.webkitAudioContext)(); const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain(); oscillator.connect(gain); gain.connect(audioContext.destination); const tones = {click:[340,.05],good:[620,.13],bad:[180,.18],final:[520,.3]}; const tone = tones[type] || tones.click; oscillator.frequency.value = tone[0]; gain.gain.setValueAtTime(.035,audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+tone[1]); oscillator.start(); oscillator.stop(audioContext.currentTime+tone[1]); } catch(error) { /* Sound is optional. */ } }
function showScreen(screenId){ document.querySelectorAll('.screen').forEach(screen => screen.classList.remove('active')); $(screenId).classList.add('active'); }
function startGame(){ const name = $('student-name').value.trim(); if(!name){ $('home-message').textContent = 'Pehle apna naam enter karo, future legend!'; return; } playSound(); game = {name,day:1,stats:{money:1000,battery:80,brain:70,energy:70,attendance:75,happiness:60},history:[],currentEvent:null,finished:false}; showScreen('game-screen'); $('player-greeting').textContent = `Hi, ${name} 👋`; showRandomEvent(); saveGame(false); }
function showRandomEvent(){ let nextEvent; do { nextEvent = events[Math.floor(Math.random()*events.length)]; } while(events.length > 1 && nextEvent === game.currentEvent); game.currentEvent = nextEvent; $('event-number').textContent = `DAY ${game.day} EVENT`; $('event-title').textContent = nextEvent.title; $('event-description').textContent = nextEvent.description; $('result-box').textContent = ''; $('next-day-button').classList.remove('ready'); $('next-day-button').disabled = true; $('choices').innerHTML = ''; nextEvent.choices.forEach((choice,index) => { const button = document.createElement('button'); button.className = 'choice-button'; button.type = 'button'; button.textContent = choice[0]; button.addEventListener('click', () => makeChoice(index)); $('choices').appendChild(button); }); updateUI(); }
function makeChoice(choiceIndex){ const choice = game.currentEvent.choices[choiceIndex]; const effects = choice[1]; Object.keys(effects).forEach(stat => { const limit = stat === 'money' ? 0 : 0; game.stats[stat] = Math.max(limit, game.stats[stat] + effects[stat]); if(stat !== 'money') game.stats[stat] = clamp(game.stats[stat],0,100); }); const result = choice[2] || resultMessages[Math.floor(Math.random()*resultMessages.length)]; const luck = Math.random(); let luckText = ''; if(luck < .27 && (choiceIndex === 1 || Math.random() < .35)){ if(luck < .135){ game.stats.brain = clamp(game.stats.brain + 10,0,100); luckText = ' 🍀 Good Luck! Brain Power +10.'; playSound('good'); } else { game.stats.brain = clamp(game.stats.brain - 6,0,100); luckText = ' 😂 Bad Luck! Sir ne wahi question puch diya jo nahi padha.'; playSound('bad'); } } else { playSound((effects.happiness || 0) >= 0 ? 'good' : 'bad'); } game.history.unshift({day:game.day,choice:choice[0]}); $('result-box').textContent = result + luckText; document.querySelectorAll('.choice-button').forEach(button => button.disabled = true); $('next-day-button').disabled = false; $('next-day-button').classList.add('ready'); updateUI(); saveGame(false); if(game.day === MAX_DAYS){ $('next-day-button').textContent = 'SEE FINAL RESULT  →'; } }
function nextDay(){ playSound(); if(game.day >= MAX_DAYS){ showFinalResult(); return; } game.day += 1; showRandomEvent(); saveGame(false); }
function updateStats(){ const statMap = {money:['money-value','money-bar','₹',''],battery:['battery-value','battery-bar','','%'],brain:['brain-value','brain-bar','',''],energy:['energy-value','energy-bar','',''],attendance:['attendance-value','attendance-bar','','%'],happiness:['happiness-value','happiness-bar','','']}; Object.keys(statMap).forEach(stat => { const [valueId,barId,prefix,suffix] = statMap[stat]; $(valueId).textContent = `${prefix}${game.stats[stat]}${suffix}`; const percentage = stat === 'money' ? clamp(game.stats.money / 10,0,100) : game.stats[stat]; $(barId).style.width = `${percentage}%`; }); }
function updateUI(){ $('day-label').textContent = `DAY ${game.day} / ${MAX_DAYS}`; $('day-progress').style.width = `${(game.day/MAX_DAYS)*100}%`; updateStats(); $('history-count').textContent = `${game.history.length}/${MAX_DAYS}`; const historyList = $('history-list'); historyList.innerHTML = ''; if(!game.history.length){ historyList.innerHTML = '<p class="empty-history">Your legendary decisions will appear here.</p>'; return; } game.history.slice(0,8).forEach(item => { const row = document.createElement('div'); row.className = 'history-item'; const day = document.createElement('span'); day.className = 'history-day'; day.textContent = `Day ${item.day}`; const decision = document.createElement('span'); decision.textContent = item.choice; row.append(day,decision); historyList.appendChild(row); }); }
function showFinalResult(){ game.finished = true; const stats = game.stats; const score = stats.attendance + stats.brain + stats.energy + stats.happiness; let result; if(stats.attendance < 35 || score < 150){ result={emoji:'💀',title:'SEMESTER SURVIVAL FAILED',description:'Attendance gayi, energy gayi, paisa gaya... semester bhi gaya.'}; } else if(stats.happiness >= 85 && stats.money < 300){ result={emoji:'☕',title:'CANTEEN KING',description:'Padhai se zyada canteen me progress hui.'}; } else if(stats.brain >= 85){ result={emoji:'💻',title:'LAB WARRIOR',description:'Code chala ya nahi, lekin VS Code kholna seekh gaye.'}; } else if(score >= 285){ result={emoji:'🏆',title:'K.N.S GP SURVIVAL LEGEND',description:'You survived the semester and still have some brain power left!'}; } else { result={emoji:'😂',title:'AVERAGE DIPLOMA STUDENT',description:'Na topper, na fail... bas somehow semester nikal gaya.'}; } $('final-emoji').textContent=result.emoji; $('final-title').textContent=result.title; $('final-description').textContent=result.description; $('final-score').textContent=`${score} / 400`; const labels=[['💰 Money',`₹${stats.money}`],['📚 Attendance',`${stats.attendance}%`],['🧠 Brain Power',stats.brain],['😴 Energy',stats.energy],['❤️ Happiness',stats.happiness]]; $('final-stats').innerHTML=labels.map(item=>`<div class="final-stat"><span>${item[0]}</span><strong>${item[1]}</strong></div>`).join(''); showScreen('final-screen'); playSound('final'); localStorage.setItem(SAVE_KEY,JSON.stringify(game)); }
function saveGame(showToast=true){ localStorage.setItem(SAVE_KEY,JSON.stringify(game)); if(showToast){ $('toast').textContent='Game saved. Semester memory secured! 💾'; $('toast').classList.add('show'); setTimeout(()=>$('toast').classList.remove('show'),2200); } }
function loadGame(){ const saved = localStorage.getItem(SAVE_KEY); if(!saved) return; try { const savedGame=JSON.parse(saved); if(savedGame.finished) return; game=savedGame; $('student-name').value=game.name; $('player-greeting').textContent=`Hi, ${game.name} 👋`; showScreen('game-screen'); showRandomEvent(); } catch(error){ localStorage.removeItem(SAVE_KEY); } }
function restartGame(){ if(confirm('Restart the semester? Your current progress will be cleared.')){ localStorage.removeItem(SAVE_KEY); game={name:'',day:1,stats:{money:1000,battery:80,brain:70,energy:70,attendance:75,happiness:60},history:[],currentEvent:null,finished:false}; $('student-name').value=''; $('home-message').textContent=''; showScreen('home-screen'); playSound(); } }
$('start-button').addEventListener('click',startGame); $('student-name').addEventListener('keydown',event=>{if(event.key==='Enter') startGame();}); $('next-day-button').addEventListener('click',nextDay); $('save-button').addEventListener('click',()=>saveGame(true)); $('restart-button').addEventListener('click',restartGame); $('play-again-button').addEventListener('click',restartGame);
const aboutModal = $('about-modal');
function closeAboutModal(){ aboutModal.hidden = true; }
$('about-button').addEventListener('click',()=>{ aboutModal.hidden = false; });
$('close-about-button').addEventListener('click',closeAboutModal);
aboutModal.addEventListener('click',event=>{ if(event.target === aboutModal) closeAboutModal(); });
document.addEventListener('keydown',event=>{ if(event.key === 'Escape' && !aboutModal.hidden) closeAboutModal(); });
window.addEventListener('DOMContentLoaded',loadGame);
