(() => {
  'use strict';
  const MUSIC_DURATION = 50;
  const characters = [
    { name: 'Character 1', look: 'Orange saree', image: 'assets/characters/character1.png', music: 'assets/music/character1.mp3' },
    { name: 'Character 2', look: 'Blue & orange', image: 'assets/characters/character2.png', music: 'assets/music/character2.mp3' },
    { name: 'Character 3', look: 'Brown saree + glasses', image: 'assets/characters/character3.png', music: 'assets/music/character3.mp3' }
  ];
  const styles = ['bollywood', 'classical', 'bhangra', 'garba'];
  const $ = (selector) => document.querySelector(selector);
  const welcome = $('#welcomeScreen'); const studio = $('#studio'); const startButton = $('#startButton');
  const dancerWrap = $('#dancerWrap'); const dancerImage = $('#dancerImage'); const fallbackDancer = $('#fallbackDancer'); const stageShadow = $('#stageShadow'); const audio = $('#audioPlayer');
  const statusPill = $('#statusPill'); const infoStatus = $('#infoStatus'); const assetNote = $('#assetNote'); const toast = $('#toast');
  let state = { character: readSetting('character', 0), style: readSetting('style', 'bollywood'), volume: readSetting('volume', 70), musicOn: readSetting('musicOn', true), status: 'READY', hasImage: false, hasMusic: false };
  let musicTimer; let toastTimer;

  function readSetting(key, fallback) { try { const value = localStorage.getItem(`dance-studio-${key}`); return value === null ? fallback : JSON.parse(value); } catch (error) { return fallback; } }
  function saveSetting(key, value) { try { localStorage.setItem(`dance-studio-${key}`, JSON.stringify(value)); } catch (error) { /* defaults remain functional */ } }
  function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2600); }
  function fallbackArt(characterIndex) { const colors = ['#d95b4d', '#3c78a0', '#8c543c']; const accent = ['#f3a44e', '#ed974d', '#b27b51']; fallbackDancer.style.setProperty('--mini-color', colors[characterIndex]); fallbackDancer.style.background = `linear-gradient(145deg, ${accent[characterIndex]} 0 38%, ${colors[characterIndex]} 39% 100%)`; }
  function renderCharacters() { const grid = $('#characterGrid'); grid.innerHTML = ''; characters.forEach((character, index) => { const card = document.createElement('button'); card.type = 'button'; card.className = `character-card${index === state.character ? ' active' : ''}`; card.setAttribute('aria-pressed', String(index === state.character)); card.innerHTML = `<figure><span class="mini-dancer" aria-hidden="true"></span><img src="${character.image}" alt="" hidden></figure><strong>${character.name}</strong><small>${character.look}</small>`; card.addEventListener('click', () => selectCharacter(index)); grid.appendChild(card); }); $('#characterCounter').textContent = `${state.character + 1} / ${characters.length}`; }
  function selectCharacter(index) { state.character = (index + characters.length) % characters.length; saveSetting('character', state.character); stopDance(false); renderCharacters(); loadCharacter(); }
  function loadCharacter() { const character = characters[state.character]; dancerImage.hidden = false; dancerImage.src = character.image; dancerImage.onload = () => { state.hasImage = true; dancerImage.style.display = 'block'; fallbackDancer.style.display = 'none'; assetNote.textContent = 'Using your local character image.'; }; dancerImage.onerror = () => { state.hasImage = false; dancerImage.style.display = 'none'; fallbackDancer.style.display = 'block'; assetNote.textContent = 'Character image not added — using built-in dancer.'; }; audio.pause(); audio.currentTime = 0; audio.src = character.music; state.hasMusic = false; audio.onloadedmetadata = () => { state.hasMusic = true; updateInfo(); }; audio.onerror = () => { state.hasMusic = false; updateInfo(); }; updateInfo(); fallbackArt(state.character); }
  function updateInfo() { const character = characters[state.character]; $('#infoDancer').textContent = character.name; $('#infoStyle').textContent = state.style[0].toUpperCase() + state.style.slice(1); $('#trackName').textContent = `${character.name} track`; $('#infoMusic').textContent = state.hasMusic ? `${character.name} Track` : 'Not available — Silent Mode'; $('#musicNote').textContent = state.hasMusic ? 'Local audio ready · 50 second session' : 'Silent mode — Add music to enable audio.'; $('#infoStatus').textContent = state.status; statusPill.textContent = state.status[0] + state.status.slice(1).toLowerCase(); }
  function setStyle(style) { state.style = styles.includes(style) ? style : 'bollywood'; saveSetting('style', state.style); document.querySelectorAll('.style-button').forEach((button) => button.classList.toggle('active', button.dataset.style === state.style)); dancerWrap.classList.remove(...styles.map((item) => `dance-${item}`)); if (state.status === 'DANCING') dancerWrap.classList.add(`dance-${state.style}`); updateInfo(); }
  function setStatus(status) { state.status = status; dancerWrap.classList.toggle('is-paused', status === 'PAUSED'); stageShadow.classList.toggle('is-paused', status === 'PAUSED'); updateInfo(); }
  async function playDance() { if (state.status === 'DANCING') return; dancerWrap.classList.remove(...styles.map((item) => `dance-${item}`)); dancerWrap.classList.add(`dance-${state.style}`); setStatus('DANCING'); if (state.musicOn && state.hasMusic) { try { audio.currentTime = 0; audio.volume = state.volume / 100; await audio.play(); clearTimeout(musicTimer); musicTimer = setTimeout(stopDance, MUSIC_DURATION * 1000); } catch (error) { showToast('Audio is unavailable, but the dance continues.'); } } else if (!state.hasMusic) showToast('Dancing in silent mode — add a local track to enable audio.'); }
  function pauseDance() { if (state.status !== 'DANCING') return; audio.pause(); setStatus('PAUSED'); }
  function stopDance(showMessage = true) { clearTimeout(musicTimer); audio.pause(); audio.currentTime = 0; dancerWrap.classList.remove(...styles.map((item) => `dance-${item}`)); setStatus('READY'); if (showMessage) showToast('Dance reset to ready.'); }
  function resetAll() { stopDance(false); state.character = 0; state.style = 'bollywood'; saveSetting('character', 0); saveSetting('style', 'bollywood'); setStyle('bollywood'); renderCharacters(); loadCharacter(); showToast('Studio settings reset.'); }
  function toggleMusic() { state.musicOn = !state.musicOn; saveSetting('musicOn', state.musicOn); $('#musicToggle').classList.toggle('active', state.musicOn); $('#musicToggle').setAttribute('aria-pressed', String(state.musicOn)); $('#musicToggle').innerHTML = `<span></span> Music ${state.musicOn ? 'on' : 'off'}`; if (!state.musicOn) audio.pause(); }
  function toggleFullscreen() { if (!document.fullscreenElement) document.documentElement.requestFullscreen?.().catch(() => showToast('Fullscreen is unavailable in this browser.')); else document.exitFullscreen?.(); }
  function startStudio() { welcome.hidden = true; studio.hidden = false; document.body.classList.add('studio-open'); }
  startButton.addEventListener('click', startStudio); $('#playButton').addEventListener('click', playDance); $('#pauseButton').addEventListener('click', pauseDance); $('#stopButton').addEventListener('click', () => stopDance()); $('#resetButton').addEventListener('click', resetAll); $('#previousButton').addEventListener('click', () => selectCharacter(state.character - 1)); $('#nextButton').addEventListener('click', () => selectCharacter(state.character + 1)); $('#musicToggle').addEventListener('click', toggleMusic); $('#fullscreenButton').addEventListener('click', toggleFullscreen);
  $('#volumeSlider').value = state.volume; $('#volumeValue').value = `${state.volume}%`; $('#volumeValue').textContent = `${state.volume}%`; $('#volumeSlider').addEventListener('input', (event) => { state.volume = Number(event.target.value); audio.volume = state.volume / 100; saveSetting('volume', state.volume); $('#volumeValue').textContent = `${state.volume}%`; });
  document.querySelectorAll('.style-button').forEach((button) => button.addEventListener('click', () => { stopDance(false); setStyle(button.dataset.style); }));
  document.addEventListener('keydown', (event) => { if (event.target.matches('input, textarea, select, button')) return; if (event.key === ' ') { event.preventDefault(); state.status === 'DANCING' ? pauseDance() : playDance(); } if (event.key === 'ArrowLeft') selectCharacter(state.character - 1); if (event.key === 'ArrowRight') selectCharacter(state.character + 1); if (/^[123]$/.test(event.key)) selectCharacter(Number(event.key) - 1); if (event.key.toLowerCase() === 'f') toggleFullscreen(); if (event.key.toLowerCase() === 'm') toggleMusic(); if (event.key.toLowerCase() === 'r') resetAll(); });
  $('#musicToggle').classList.toggle('active', state.musicOn); $('#musicToggle').setAttribute('aria-pressed', String(state.musicOn)); $('#musicToggle').innerHTML = `<span></span> Music ${state.musicOn ? 'on' : 'off'}`; setStyle(state.style); renderCharacters(); loadCharacter();
})();